Discord Webhooks:
  On Job Create:
    Enabled: false
    URL: ''
    Title: 'New Job Posted!'
    Message: '%employer% needs %goal% and will pay %reward%'
    
# Define a maximum time after which a job will be automatically deleted.
# ATTENTION: All time units must be plural(seconds, days, etc) and the maximum unit is days!
Auto Delete Jobs:
  Enabled: false
  After: 1 days
  
# Define the default notification policy once a job is created; Players set their own using "/emp addnotifiers".
# 'None' - Don't notify about any job.
# 'All Jobs' - Notifications for all jobs by default.
# 'Material Subscriptions' - Notify only if the created job's reward includes items that the player subscribed for.
Default Job Add Notifier: All Jobs