name: EmployMe-Premium
main: dte.employme.EmployMe
version: ${project.version}
description: Automate resources gathering by employing players.
softdepend: [Vault]
api-version: 1.16
author: DavidTheExplorer